---
default:
  image: 'python:3.13'
  before_script:
    - pip install tox

stages:
  - build
  - test

lint:
  stage: build
  script:
    - tox -e gitlint
    - tox -e yamllint,markdownlint

test-tox:
  stage: test
  script:
    - tox

test-tf:
  stage: test
  image:
    name: 'ghcr.io/opentofu/opentofu:$VERSION'
    entrypoint:
      - ""
  parallel:
    matrix:
      - VERSION:
          - "1.11"
          - "1.10"
          - "1.9"
  before_script: []
  script:
    - tofu -chdir=tf init
    - tofu -chdir=tf validate
