[tox]
envlist = gitlint,yamllint,markdownlint,ansiblelint

[testenv]
skip_install = True
allowlist_externals =
  {toxinidir}/scripts/*

[testenv:gitlint]
envdir = {toxworkdir}/gitlint
deps = gitlint
commands = gitlint {posargs}

[testenv:yamllint]
envdir = {toxworkdir}/yamllint
deps = yamllint
commands = yamllint {toxinidir}

[testenv:markdownlint]
envdir = {toxworkdir}/markdownlint
deps =
  pymarkdownlnt!=0.9.13
commands = pymarkdown -c .pymarkdown.json scan .

[testenv:ansiblelint]
deps =
  -r {toxinidir}/ansible/requirements.txt
  ansible-lint
commands =
  ansible-galaxy collection install -r {toxinidir}/ansible/requirements.yaml
  ansible-lint {toxinidir}/ansible/build.yaml {toxinidir}/ansible/teardown.yaml {posargs}

[testenv:ansible{2.16,2.18,2.19,2.20}-lint]
deps =
  ansible2.16: ansible-core<2.17
  ansible2.18: ansible-core<2.19
  ansible2.19: ansible-core<2.20
  ansible2.20: ansible-core<2.21
  ansible-lint
commands =
  ansible-galaxy collection install -r {toxinidir}/ansible/requirements.yaml
  ansible-lint {toxinidir}/ansible/build.yaml {toxinidir}/ansible/teardown.yaml {posargs}

[testenv:ansible-playbook]
passenv = OS_*
deps = -r {toxinidir}/ansible/requirements.txt
commands =
  ansible-galaxy collection install -r {toxinidir}/ansible/requirements.yaml
  ansible-playbook {posargs}

[testenv:ansible{2.16,2.18,2.19,2.20}-playbook-{epoxy,flamingo,gazpacho}]
passenv = OS_*
deps =
  ansible2.18: ansible-core<2.19
  ansible2.19: ansible-core<2.20
  ansible2.20: ansible-core<2.21
  epoxy: openstacksdk<4.5
  flamingo: openstacksdk<4.8
  gazpacho: openstacksdk<4.11
commands =
  ansible-galaxy collection install -r {toxinidir}/ansible/requirements.yaml
  ansible-playbook {posargs}

[testenv:ansible{2.16}-playbook-{caracal}]
passenv = OS_*
deps =
  ansible2.16: ansible-core<2.17
  caracal: openstacksdk<3.1
commands =
  ansible-galaxy collection install -r {toxinidir}/ansible/requirements.yaml
  ansible-playbook {posargs}

[testenv:openstack]
passenv = OS_*
deps = -r {toxinidir}/heat/requirements.txt
commands =
  openstack {posargs}

[testenv:openstack-{caracal,epoxy,flamingo,gazpacho}]
passenv = OS_*
deps =
  caracal: python-openstackclient<7.0
  caracal: python-heatclient<4.0
  epoxy: python-openstackclient<8.0
  epoxy: python-heatclient<4.3
  flamingo: python-openstackclient<8.3
  flamingo: python-heatclient<5.0
  gazpacho: python-openstackclient<9.1
  gazpacho: python-heatclient<5.2
commands =
  openstack {posargs}
