[tox]
envlist = gitlint,yamllint,markdownlint

[testenv]
skip_install = True
allowlist_externals =
  {toxinidir}/scripts/*

[testenv:gitlint]
envdir = {toxworkdir}/gitlint
deps = gitlint
commands = gitlint {posargs}

[testenv:yamllint]
envdir = {toxworkdir}/yamllint
deps = yamllint
commands = yamllint {toxinidir}

[testenv:markdownlint]
envdir = {toxworkdir}/markdownlint
deps =
  pymarkdownlnt!=0.9.13
commands = pymarkdown -c .pymarkdown.json scan README.md

[testenv:openstack]
passenv = OS_*
deps =
  python-openstackclient
  python-heatclient
  python-neutronclient
commands =
  openstack {posargs}
