---
- name: "Create a bastion host"
  when: "not(teardown | bool)"
  block:

    - name: "Create port"
      openstack.cloud.port:
        state: present
        name: "{{ stack_name }}-bastion-port"
        network: "{{ _network.network.id }}"
        security_groups:
          - "{{ _security_group.security_group.id }}"
      register: "_bastion_port"

    - name: "Create server"
      openstack.cloud.server:
        state: present
        name: "{{ stack_name }}-bastion"
        boot_from_volume: true
        config_drive: true
        flavor: "{{ flavor }}"
        image: "{{ image }}"
        key_name: "{{ _keypair.keypair.id }}"
        nics:
          - port-id: "{{ _bastion_port.port.id }}"
        volume_size: "{{ volume_size }}"
        userdata: |
          #cloud-config
          package_update: true
          package_upgrade: true
          package_reboot_if_required: true
          users:
            - default
            - name: cleura
              ssh_redirect_user: true
      register: "_bastion_host"

    - name: "Assign a floating IP address"
      openstack.cloud.floating_ip:
        state: present
        network: "{{ public_net }}"
        server: "{{ _bastion_host.server.id }}"
      register: "_bastion_floating_ip"

- name: "Remove the bastion host"
  when: "teardown | bool"
  block:

    - name: "Delete server"
      openstack.cloud.server:
        state: absent
        name: "{{ stack_name }}-bastion"

    - name: "Delete port"
      openstack.cloud.port:
        state: absent
        name: "{{ stack_name }}-bastion-port"
