---
- name: "Tear down Cleura Cloud resources"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    teardown: true

  tasks:
    - name: "Manage the Pad Ramp"
      ansible.builtin.import_tasks: "ramp.yaml"
    - name: "Manage security groups"
      ansible.builtin.import_tasks: "secgroups.yaml"
    - name: "Manage network resources"
      ansible.builtin.import_tasks: "network.yaml"
    - name: "Manage key pair"
      ansible.builtin.import_tasks: "keypair.yaml"
